export const LOGIN_USER_WITH_GOOGLE = "LOGIN_USER_WITH_GOOGLE"
export const LOGIN_USER_WITH_FACEBOOK = "LOGIN_USER_WITH_FACEBOOK"
export const GET_QUESTION = "GET_QUESTION"
export const UESR_REGISTER_AND_LOGIN = "UESR_REGISTER_AND_LOGIN"